//Register a user
POST http://localhost:1000/users/register
Content-Type: application/json

{
    "name":"Rachel",
    "email":"rachel@gmail.com",
    "password":"Qwerty@401",
    "role":"Government Official"
}


####
POST http://localhost:1000/users/login
Content-Type: application/json

{
    "email":"gitonga@gmail.com",
    "password":"Qwerty@401"
}

####
PUT http://localhost:1000/users/forgotPassword/gitonga@gmail.com
Content-Type: application/json

{
    "password":"Qwerty10?"
}


####
GET http://localhost:1000/user/notApproved


####

GET http://localhost:1000/users/approved