CREATE TABLE PollResponses(
    id VARCHAR(255) PRIMARY KEY,
    pollId VARCHAR(255) NOT NULL,
    userId VARCHAR(255) NOT NULL,
    pollChoiceId VARCHAR(255) NOT NULL,
    FOREIGN KEY (pollId) REFERENCES Polls(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE NO ACTION,
    FOREIGN KEY (pollChoiceId) REFERENCES pollChoices(id) ON DELETE NO ACTION
);
